### ISSUE TITLE
target Java via Graal?

### ISSUE THREAD

**Issue by haroldcarr** [JKTKops/Write-You-a-Haskell-2#1]
You say you are targetting Java.

Do you plan to use Graal?

[https://www.graalvm.org/](https://www.graalvm.org/)

**Comment by JKTKops** [comment]
The plan is merely to produce Java source code.

Note that I'm not aiming to produce a "translation" to Java, but rather I intend to use Java as a host for the Runtime System. Of course, in GHC, C--/C host the runtime system, and that produces much better machine code than what I expect to get here.

Either way, once the compiler has produced Java source, it should be able to run on any JVM. My hope is that I can compile STG into code that is valid Java 7 and Java 8, so that there is as little interopability problems across that gap as possible. I haven't seen Graal before, but it seems at first glance that Graal would be able to run the code. I'll include a note when we get there!

Eventually I will probably try and add a backend that can generate native code. I'm still a College/University student and while my primary interest is compilers, I still don't have much experience working on them, so native code generation is outside the scope of my _current_ plans.

**Comment by haroldcarr** [comment]
I encourage you to look deeper in Graal and its Truffle subsystem.   I think you will find the combination to be a better target than generating Java code.

Best wishes.

**Comment by JKTKops** [comment]
Thank you for the recommendation. I'll be sure to check it out! :)
